In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,maximum_temperature,minimum_temperature,average_temperature,precipitation,snow_fall,snow_depth,pickup_seconds,pickup_minutes,pickup_hour,pickup_weekday,pickup_day,pickup_month
0,1.0,-73.982155,40.767937,-73.964630,40.765602,455.0,51.0,40.0,45.5,0.29,0.0,0.000000,55.0,24.0,17.0,0.0,14.0,3.0
1,1.0,-73.980415,40.738564,-73.999481,40.731152,663.0,46.0,37.0,41.5,0.35,0.0,0.000000,35.0,43.0,0.0,6.0,12.0,6.0
2,1.0,-73.979027,40.763939,-74.005333,40.710087,2124.0,28.0,16.0,22.0,0.00,0.0,0.627881,24.0,35.0,11.0,1.0,19.0,1.0
3,1.0,-74.010040,40.719971,-74.012268,40.706718,429.0,83.0,66.0,74.5,0.40,0.0,0.000000,31.0,32.0,19.0,2.0,6.0,4.0
4,1.0,-73.973053,40.793209,-73.972923,40.782520,435.0,55.0,38.0,46.5,0.00,0.0,0.000000,55.0,30.0,13.0,5.0,26.0,3.0

Так как новые временные признаки были получены в предыдущей сессии, в этой сессии мы сконструируем признак расстояние, вычислив расстояние в километрах между координатами pickup и координатами dropoff.

In [9]:
def calculate_distance(row):
    
    lon1, lon2 = np.radians(row["pickup_longitude"]), np.radians(row["dropoff_longitude"])
    lat1, lat2 = np.radians(row["pickup_latitude"]), np.radians(row["dropoff_latitude"])
    
      
    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
 
    c = 2 * np.arcsin(np.sqrt(a))
    
    # Radius of earth in kilometers. Use 3956 for miles
    r = 6371
      
    # calculate the result
    return(c * r)

In [15]:
df["distance"] = df.apply(calculate_distance, axis=1)

In [17]:
df.iloc[5]

passenger_count        1.518806
pickup_longitude       1.518806
pickup_latitude        1.518806
dropoff_longitude      1.518806
dropoff_latitude       1.518806
trip_duration          1.518806
maximum_temperature    1.518806
minimum_temperature    1.518806
average_temperature    1.518806
precipitation          1.518806
snow_fall              1.518806
snow_depth             1.518806
pickup_seconds         1.518806
pickup_minutes         1.518806
pickup_hour            1.518806
pickup_weekday         1.518806
pickup_day             1.518806
pickup_month           1.518806
distance               0.000000
Name: 5, dtype: float64

In [16]:
df["distance"]

0         1.498521
1         1.805507
2         6.385098
3         1.485498
4         1.188588
5         0.000000
6         1.326279
7         5.714981
8         1.310353
9         5.121162
10        3.806139
11        3.773096
12        1.859483
13        0.991685
14        6.382836
15        0.656578
16        0.000000
17        2.538672
18        4.605201
19        1.303271
20        2.505926
21        1.724550
22        2.067085
23        4.874792
24        0.000000
25        0.000000
26        6.056109
27        3.738742
28        2.524849
29        0.000000
            ...
102691    0.891434
102692    2.756027
102693    0.000000
102694    3.487243
102695    1.068303
102696    0.903117
102697    0.884831
102698    0.918865
102699    1.617458
102700    1.207723
102701    1.249831
102702    0.938121
102703    1.299220
102704    1.294331
102705    1.995994
102706    0.000000
102707    2.530216
102708    0.000000
102709    0.504576
102710    1.406940
102711    3.085642
102712    0.000000
102713    5.320043
102714    2.833857
102715    0.947286
102716    6.856204
102717    0.000000
102718    0.953734
102719    1.106492
102720    0.779903
Name: distance, Length: 102721, dtype: float64